In [86]:
import numpy as np

# Домашнее задание к уроку 7


## Задание 1

Даны значения величины заработной платы заемщиков банка (zp) и значения их поведенческого кредитного скоринга (ks): zp = [35, 45, 190, 200, 40, 70, 54, 150, 120, 110], ks = [401, 574, 874, 919, 459, 739, 653, 902, 746, 832]. Используя математические операции, посчитать коэффициенты линейной регрессии, приняв за X заработную плату (то есть, zp - признак), а за y - значения скорингового балла (то есть, ks - целевая переменная). Произвести расчет как с использованием intercept, так и без.

In [87]:
X = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
y = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832]) 

Вычисление коэффициентов линейной регрессии **с intercept** (с помощью математических операций)

In [88]:
n = len(X)
n

10

In [89]:
# вычисление коэффициента b
b = (np.mean(X * y) - np.mean(X) * np.mean(y)) / (np.mean(X ** 2) - np.mean(X) ** 2)
b

2.620538882402765

In [90]:
# вычисление коэффициента a
a = np.mean(y) - b * np.mean(X)
a

444.1773573243596

Вычисление коэффициентов линейной регрессии **без intercept** (с помощью матричного метода)

In [91]:
# преобразование вектора-строки X в вектор-столбец
X = X.reshape((10, 1))
X


array([[ 35],
       [ 45],
       [190],
       [200],
       [ 40],
       [ 70],
       [ 54],
       [150],
       [120],
       [110]])

In [92]:
# преобразование вектора-строки Y в вектор-столбец
y = y.reshape((10, 1))
y


array([[401],
       [574],
       [874],
       [919],
       [459],
       [739],
       [653],
       [902],
       [746],
       [832]])

In [93]:
# Вычисление коэффициента beta_1
B = np.dot(np.linalg.inv(np.dot(X.T, X)), X.T @ y)
B

array([[5.88982042]])

**Ответ**: Уравнение линейной регрессии **с intercept**: $y = 2,621x+444,177$<br>
Уравнение линейной регрессии **без intercept**: $y=5,88x$


## Задание 2

Посчитать коэффициент линейной регрессии при заработной плате (zp), используя градиентный спуск (без intercept).

In [94]:
X = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
y = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832]) 

In [95]:
# функция ошибок
def mse_(B1, y = y, X = X, n = 10):
  return np.sum((B1 * X - y) ** 2) / n

In [96]:
# начальное значение коэффициента beta_1
B1 = 0.1
# скорость обучения
alpha = 1e-6

In [97]:
for i in range(10000):
  B1 -=alpha * (2 / n) * np.sum((B1 * X - y) * X)
  if i % 1000 == 0:
    print(f'Iteration: {i},B1 = {B1}, mse = {mse_(B1)}')


Iteration: 0,B1 = 0.25952808, mse = 493237.7212546963
Iteration: 1000,B1 = 5.8898204201285544, mse = 56516.85841571941
Iteration: 2000,B1 = 5.889820420132673, mse = 56516.85841571943
Iteration: 3000,B1 = 5.889820420132673, mse = 56516.85841571943
Iteration: 4000,B1 = 5.889820420132673, mse = 56516.85841571943
Iteration: 5000,B1 = 5.889820420132673, mse = 56516.85841571943
Iteration: 6000,B1 = 5.889820420132673, mse = 56516.85841571943
Iteration: 7000,B1 = 5.889820420132673, mse = 56516.85841571943
Iteration: 8000,B1 = 5.889820420132673, mse = 56516.85841571943
Iteration: 9000,B1 = 5.889820420132673, mse = 56516.85841571943


**Ответ:** Уравнение линейной регрессии **без intercept**, полученное методом градиентного спуска: $y=5,88x$

## Задание 3

В каких случаях для вычисления доверительных интервалов и проверки статистических гипотез используется таблица значений функции Лапласа, а в каких - таблица критических точек распределения Стьюдента?

**Ответ:** 1) На таблице Лапласа основан z-критерий, который используется при проверке статистических гипотез в случае, если **известено** среднее квадратичное отклонение или дисперсия генеральной совокупности. <br>
2) На таблице критических точек распределения Стьюдента основан критерий Стьюдента, который используется при проверке статистических гипотез в случае, если **не известно** среднее квадратичное отклонение или дисперсия генеральной совокупности. <br>



## Задание 4*

Произвести вычисления как в пункте 2, но с вычислением intercept. Учесть, что изменение коэффициентов должно производиться на каждом шаге одновременно (то есть изменение одного коэффициента не должно влиять на изменение другого во время одной итерации).

In [98]:
X = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
y = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832]) 

In [99]:
# коэффициенты beta_0 и beta_1
B0 = 0.1
B1 = 0.1

In [100]:
# скорость обучения
alpha = 5e-5

In [101]:
# функция ошибок
def mse_(B0, B1, y = y,X = X, n = 10):
  return np.sum((B0 + B1 * X - y) ** 2) / n

In [102]:
for i in range(750000):
  y_p = B0 + B1 * X
  B0 -=alpha * (2 / n) * np.sum((y_p - y))
  B1 -=alpha * (2 / n) * np.sum((y_p - y) * X)
  if i % 30000 == 0:
    print(f'Iteration: {i},B_0 = {B0}, B1 = {B1}, mse = {mse_(B0, B1)}')

Iteration: 0,B_0 = 0.169966, B1 = 8.07539, mse = 122360.8044853729
Iteration: 30000,B_0 = 236.72238797814268, B1 = 4.147499177901624, mse = 17387.534091270718
Iteration: 60000,B_0 = 347.251033231717, B1 = 3.333959481314144, mse = 8853.523054754403
Iteration: 90000,B_0 = 398.89180773391786, B1 = 2.9538605492800123, mse = 6990.625380056672
Iteration: 120000,B_0 = 423.0192145710213, B1 = 2.7762721676196023, mse = 6583.971611794087
Iteration: 150000,B_0 = 434.2919301004539, B1 = 2.6932999973691483, mse = 6495.202760188238
Iteration: 180000,B_0 = 439.55872550311335, B1 = 2.654534054621566, mse = 6475.825320138674
Iteration: 210000,B_0 = 442.01945767904283, B1 = 2.636421977854534, mse = 6471.595399664535
Iteration: 240000,B_0 = 443.1691516349953, B1 = 2.6279597220298276, mse = 6470.672046157995
Iteration: 270000,B_0 = 443.7063072853679, B1 = 2.6240060189529295, mse = 6470.4704864115965
Iteration: 300000,B_0 = 443.9572751113981, B1 = 2.6221587847940984, mse = 6470.426487736031
Iteration: 3300

**Ответ**: Уравнение линейной регрессии **с intercept**, полученное методом градиентного спуска:: $y = 2,621x+444,177$